### ISSUE TITLE
Add methods send to module Credentials

### ISSUE THREAD

**Issue by kayqueGovetri** [botcity-dev/botcity-maestro-sdk-js#16]
With the release of the new version of <aestro, calls to enter and capture platform credentials are available. You will need to implement the following methods:

- getCredential
- create credential
- getCredentials
- createCredentials
- updateCredential
- getValueCredential
- deleteCredential

**Comment by hhslepicka** [comment]
Let's focus on the following ones:
- `getCredential(bucketName, key)`
- `createCredential(bucketName, key, value)`

Update is not supported and I believe we should leave `delete` operation to the Maestro UI.
