### ISSUE TITLE
Error when server has an ending `/`

### ISSUE THREAD

**Issue by hhslepicka** [botcity-dev/botcity-maestro-sdk-js#20]
**Describe the bug**
SDK fails when the server URL has an ending `/`.
Example: `https://developers.botcity.dev/`

**Comment by kayqueGovetri** [comment]
Resolved in commit [bdfdeaf](https://github.com/botcity-dev/botcity-maestro-sdk-js/commit/bdfdeaf88965471dfa732171784fba99df1a2238)
