### ISSUE TITLE
npx js-template-cli  failed while installing library

### ISSUE THREAD

**Issue by astubiggi** [botcity-dev/botcity-maestro-sdk-js#26]
**Describe the bug**
While installing from cli, npx failed. While taking at the logs, i found out that its failing while trying to install nut-tree.

i have shared the log bellow

657 timing idealTree:node_modules/@botcity/botcity-framework-core/node_modules/axios Completed in 0ms
658 timing idealTree:node_modules/bl/node_modules/readable-stream Completed in 0ms
659 timing idealTree:node_modules/readable-web-to-node-stream/node_modules/readable-stream Completed in 0ms
660 timing idealTree:node_modules/tar-stream/node_modules/readable-stream Completed in 0ms
661 timing idealTree:buildDeps Completed in 6779ms
662 timing idealTree:fixDepFlags Completed in 2ms
663 timing idealTree Completed in 6823ms
664 timing command:install Completed in 6836ms
665 verbose stack HttpErrorGeneral: 404 Not Found - GET https://registry.npmjs.org/@nut-tree%2fnut-js - Not found
665 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\lib\check-response.js:95:15
665 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
665 verbose stack     at async RegistryFetcher.packument (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\registry.js:87:19)
665 verbose stack     at async RegistryFetcher.manifest (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\registry.js:118:23)
665 verbose stack     at async Promise.all (index 1)
665 verbose stack     at async #buildDepStep (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1034:5)
665 verbose stack     at async Arborist.buildIdealTree (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:196:7)
665 verbose stack     at async Promise.all (index 1)
665 verbose stack     at async Arborist.reify (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:159:5)
665 verbose stack     at async Install.exec (C:\Program Files\nodejs\node_modules\npm\lib\commands\install.js:152:5)
666 verbose statusCode 404
667 verbose pkgid @nut-tree/nut-js@^2.3.0
668 verbose cwd C:\Users\Administrator\Desktop\tmp
669 verbose Windows_NT 10.0.20348
670 verbose node v20.10.0
671 verbose npm  v10.2.3
672 error code E404
673 error 404 Not Found - GET https://registry.npmjs.org/@nut-tree%2fnut-js - Not found
674 error 404
675 error 404  '@nut-tree/nut-js@^2.3.0' is not in this registry.
676 error 404
676 error 404 Note that you can also install from a
677 error 404 tarball, folder, http url, or git url.
678 verbose exit 1

**Comment by kayqueGovetri** [comment]
Hello @astubiggi, Thanks for the bug notice.

We identified the problem in the library we use in the keyboard and mouse interaction layer. We adjusted some dependencies in our core framework.

When trying to install again, try to use the node 16 version if installing with 20 gives any problems.
